services:
  - type: web
    name: raven-api
    env: python
    plan: free
    buildCommand: |
      echo "python-3.11.0" > runtime.txt
      python3.11 -m pip install -r cfg/prd/requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://raven-frontend-mb0t.onrender.com

  - type: web
    name: raven-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://raven-api.onrender.com
